name: Backend CD - Deploy Backend Services to AKS

on:
  workflow_run:
    workflows: ["Backend CI - Test, Build, Push Images to ACR"]
    types: [completed]

jobs:
  deploy_backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set Kubernetes context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Attach ACR to AKS
        run: |
          az aks update \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --attach-acr ${{ secrets.ACR_NAME }}

      - name: Deploy Backend Infrastructure
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml

      - name: Deploy Backend Microservices
        run: |
          cd k8s/
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml

      - name: Update Deployments with New Images
        run: |
          kubectl set image deployment/product-deployment \
            product=${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.event.workflow_run.head_sha }}
          kubectl set image deployment/order-deployment \
            order=${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.event.workflow_run.head_sha }}

      - name: Wait for Rollout Completion
        run: |
          kubectl rollout status deployment/product-deployment
          kubectl rollout status deployment/order-deployment

      - name: Logout from Azure
        run: az logout
